const assert=require('node:assert/strict');const {create}=require('../web/operations-model.js');
const m=create();let count=0;m.subscribe(()=>count++);
const id=m.createTask('Prepare encounter handoff','Coordinator',[],true);m.advance(id);m.advance(id);let t=m.state.tasks[0];assert.equal(t.status,'waiting');
m.reply(id,'Here is more context');assert.equal(t.status,'waiting');m.reply(id,'Attached',[{name:'signed.txt',bytes:20,hash:'abc'}]);assert.equal(t.status,'running');m.action(id,'pause');m.advance(id);assert.equal(t.stage,1);m.action(id,'resume');m.advance(id);m.advance(id);assert.equal(t.status,'review');assert.equal(t.output.mode,'frontend_simulation');
m.reply(id,'Use the revised destination');assert.equal(t.output,null);assert.equal(t.status,'running');m.advance(id);m.advance(id);m.action(id,'approve');assert.equal(t.status,'completed');assert.throws(()=>m.reply(id,'edit closed'));
const sid=m.saveSchedule({name:'Morning check',prompt:'Check appointments',frequency:'weekdays',time:'08:00',day:'1',enabled:true});m.toggleSchedule(sid);assert.equal(m.state.schedules[0].enabled,false);const tid=m.runSchedule(sid);assert.ok(m.state.tasks.find(t=>t.id===tid));m.saveSchedule({name:'Evening check',prompt:'Check appointments',frequency:'daily',time:'17:00',day:'1',enabled:true},sid);assert.equal(m.state.schedules.length,1);m.deleteSchedule(sid);assert.equal(m.state.schedules.length,0);
const slack=m.receiveSlack('Please prepare this document',[{name:'test.pdf',bytes:50}]);assert.equal(m.state.inbox[0].taskId,slack);m.action(slack,'cancel');m.advance(slack);assert.equal(m.state.tasks[0].status,'cancelled');assert.throws(()=>m.action(slack,'resume'));
const restored=create(JSON.parse(JSON.stringify(m.state)));assert.equal(restored.state.tasks.length,3);assert.throws(()=>m.settings({clinic:'Clinic',timezone:'fake/zone'}));assert.ok(count>10);m.reset();assert.equal(m.state.tasks.length,0);
console.log('PASS: evidence waits, pause/resume, version invalidation, review, schedule CRUD, Slack intake, cancellation and local state restoration.');
