/* Frontend-only fixture adapter. Replace with authenticated service responses on GB10. */
(function(root){
const transcript='This is a synthetic encounter recording. The patient confirms the scheduled visit and administrative check-in. The clinician will review the visit summary and provide the signed encounter document.';
const summary='The patient confirmed the scheduled visit and completed administrative check-in. The clinician will review the summary and supply the signed encounter document.';
const initial=()=>({run:Date.now(),revision:1,role:'clinician',checkedIn:false,consent:false,profile:{preferredName:"P-104",contactPreference:"Local kiosk",version:1},transcript:null,audio:null,draft:null,review:null,completed:false,document:null,request:false,packet:'BLOCKED',manifest:null,ack:false,events:[{at:new Date().toISOString(),text:'Demo started. Pre-visit history is seeded context. Patient check-in is pending.',kind:'fixture_context'}]});
function create(){let s=initial();const listeners=new Set();let timer;const emit=()=>listeners.forEach(f=>f(s));const event=(text,kind='simulation')=>s.events.push({at:new Date().toISOString(),text,kind});const requireRole=r=>{if(s.role!==r)throw Error('Switch to the '+r+' demo session first.');};
const invalid=()=>{s.revision++;s.packet='BLOCKED';s.manifest=null;s.ack=false;clearTimeout(timer);};
const unresolved=()=>[...(!s.checkedIn?[{item:'Patient check-in',owner:'Patient'}]:[]),...(!s.consent?[{item:'Audio acknowledgment',owner:'Patient'}]:[]),...(!s.review||s.review.version!==s.draft?.version||s.review.text!==s.draft?.text?[{item:'Current summary review',owner:'Dr. Chen'}]:[]),...(!s.completed?[{item:'Encounter completion',owner:'Dr. Chen'}]:[]),...(!s.document?[{item:'Signed encounter document',owner:'Dr. Chen'}]:[])];
const ready=()=>s.checkedIn&&s.consent&&s.completed&&s.draft&&s.review?.version===s.draft.version&&s.review?.text===s.draft.text&&s.document?.encounter==='ENC-104'&&s.document?.status==='signed'&&s.document?.attested;
function resume(){if(!ready()){emit();return;}const run=s.run,rev=s.revision;s.packet='ASSEMBLING';event('Fixture event resumed packet assembly.');emit();timer=setTimeout(()=>{if(s.run!==run||s.revision!==rev||!ready())return;s.packet='VERIFYING';event('Comparing current in-memory fixture versions.');emit();timer=setTimeout(()=>{if(s.run!==run||s.revision!==rev||!ready())return;s.packet='READY_FOR_COORDINATOR_REVIEW';s.manifest={packet_id:'PACKET-104',encounter_id:'ENC-104',requirements_version:1,execution_mode:'frontend_simulation',source_revision:rev,summary_version:s.draft.version,reviewed_text:s.review.text,review:{...s.review},patient_profile:{...s.profile},unresolved_items:[],document:s.document,source_ids:['APT-104-v2','CHECKIN-104-v1','ELIG-104-v2','SUMMARY-104-v'+s.draft.version,s.document.id,'BILLING-104-v1'],billing:{code:'DEMO-ONLY',amount:125,currency:'USD',synthetic:true},verified_at:new Date().toISOString(),independent_backend_verification:false,claim_submitted:false};event('Mock packet ready for coordinator review; Slack handoff preview generated (not sent).');emit();},550);},550);}
const api={get state(){return s;},get unresolved(){return unresolved();},subscribe(f){listeners.add(f);return()=>listeners.delete(f);},reset(){requireRole('operator');clearTimeout(timer);s=initial();s.role='operator';emit();},switchRole(role){if(!['clinician','patient','coordinator','operator'].includes(role))throw Error('Unknown role');s.role=role;emit();},
 replay(){requireRole('clinician');if(!s.checkedIn||!s.consent)throw Error('Patient check-in and audio acknowledgment are required.');invalid();s.transcript={id:'TRANSCRIPT-104',text:transcript,execution_mode:'fixture_replay',source:'SCRIPT-104',timestamps:['00:00','00:05','00:09']};s.draft={id:'SUMMARY-104',version:(s.draft?.version||0)+1,text:summary,source:'TRANSCRIPT-104'};s.review=null;event('Transcript and draft loaded from fixture. No ASR or LLM executed.','fixture_replay');emit();},
 setAudio(meta){requireRole('clinician');if(!s.checkedIn||!s.consent)throw Error('Patient check-in and audio acknowledgment are required.');invalid();s.audio=meta;s.transcript=null;s.draft=null;s.review=null;event('WAV selected locally. Live transcription unavailable until GB10 adapter is connected.');emit();},
 edit(text,version){requireRole('clinician');if(!s.draft||version!==s.draft.version)throw Error('Stale draft version.');if(!text.trim())throw Error('Summary cannot be empty.');invalid();s.draft={...s.draft,text:text.trim(),version:version+1};s.review=null;event('Edited draft saved; prior review invalidated.');emit();},
 review(decision,version){requireRole('clinician');if(!s.draft||version!==s.draft.version)throw Error('Stale draft version.');if(!['accept','reject'].includes(decision))throw Error('Invalid review');if(decision==='accept'&&s.review?.version===version)return;invalid();s.review=decision==='accept'?{version,text:s.draft.text,actor:'Dr. Chen',at:new Date().toISOString()}:null;event(decision==='accept'?'Clinician accepted exact summary version '+version+'.':'Clinician rejected draft; packet remains blocked.');resume();},
 complete(){requireRole('clinician');if(!s.review||s.review.version!==s.draft?.version)throw Error('Review the current summary first.');if(s.completed)return;invalid();s.completed=true;event('encounter.completed fixture event.');if(!s.document){s.request=true;event('Missing-document request generated for Dr. Chen. Slack preview only, not sent.');}resume();},
 upload(doc){requireRole('clinician');if(!s.request)throw Error('Complete the encounter to create a document request.');if(doc.encounter!=='ENC-104'||doc.case_id!=='CASE-104')throw Error('Wrong case or encounter.');if(doc.assigned!=='Dr. Chen')throw Error('Wrong assigned clinician.');if(doc.status!=='signed'||!doc.attested)throw Error('Signed status and synthetic clinician attestation are required.');if(!doc.hash)throw Error('Document hash is missing.');if(s.document?.hash===doc.hash)return;invalid();s.document={...doc,version:(s.document?.version||0)+1};event('Synthetic document validated and hashed locally; upload event simulated.');resume();},
 checkIn(consent,profile=s.profile){requireRole('patient');if(Object.keys(profile).some(k=>!['preferredName','contactPreference','version'].includes(k)))throw Error('Only administrative profile fields are allowed.');if(!profile.preferredName?.trim()||profile.preferredName.length>60||!['Local kiosk','Staff follow-up'].includes(profile.contactPreference))throw Error('Confirm a valid preferred name and contact preference.');if(!consent)throw Error('Acknowledge the synthetic audio demonstration.');if(s.checkedIn&&s.consent)return;invalid();s.checkedIn=true;s.consent=true;s.profile={preferredName:profile.preferredName.trim(),contactPreference:profile.contactPreference,version:s.profile.version+1};event('Patient confirmed administrative fields and audio acknowledgment; visit-bound check-in simulated.');resume();},
 acknowledge(){requireRole('coordinator');if(s.packet!=='READY_FOR_COORDINATOR_REVIEW')throw Error('Packet is blocked.');if(s.ack)return;s.ack=true;event('Coordinator acknowledged the handoff separately from readiness.');emit();},
 invalidate(){requireRole('operator');invalid();s.document=null;event('Source document removed by operator fixture: readiness invalidated.');emit();}
};return api;}
const exported={create,initial};if(typeof module!=='undefined')module.exports=exported;else root.CadenceModel=exported;
})(typeof window!=='undefined'?window:globalThis);
