/* Device-local demonstration adapter. Never invokes Slack, models or the filesystem. */
(function(root){
const initial=()=>({version:1,tasks:[],schedules:[],inbox:[],settings:{clinic:'Cadence Clinic',timezone:'America/New_York',hours:'08:00–17:00',approval:true,channel:'#clinic-operations',destination:'Clinic / Encounter documents',notifications:true},events:[]});
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
function create(saved){let s=saved&&saved.version===1?saved:initial();const listeners=new Set();const emit=()=>listeners.forEach(fn=>fn(s));const log=(text,taskId)=>s.events.unshift({id:uid(),at:new Date().toISOString(),text,taskId});const task=id=>{const t=s.tasks.find(t=>t.id===id);if(!t)throw Error('Task not found.');return t};
const api={get state(){return s},subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)},
createTask(text,source='Coordinator',files=[],requiresDocument=false){if(!text.trim())throw Error('Describe the task first.');const t={id:uid(),title:text.trim().slice(0,90),prompt:text.trim(),source,created:new Date().toISOString(),status:'running',stage:0,files,requiresDocument,messages:[{role:'user',text:text.trim()}],events:[{text:'Task assigned. Demo agent plan created.',at:new Date().toISOString()}],approved:false,output:null};s.tasks.unshift(t);log('Task assigned from '+source,t.id);emit();return t.id},
advance(id){const t=task(id);if(t.status!=='running')return;if(t.stage===0){t.stage=1;t.messages.push({role:'bot',text:'I’ve split this demo into three roles: plan the work, collect its evidence, and prepare the handoff.'});}else if(t.stage===1&&t.requiresDocument&&!t.files.length){t.status='waiting';t.messages.push({role:'bot',text:'A supporting document is needed. Attach synthetic evidence below to continue the demonstration.'});}else if(t.stage<2){t.stage=2;}else{t.status=s.settings.approval?'review':'completed';t.output={task:t.prompt,mode:'frontend_simulation',sources:t.files.map(f=>({name:f.name,bytes:f.bytes})),destination:s.settings.destination,note:'Demonstration handoff plan. No clinical analysis, model execution, Slack delivery or local-system write occurred.'};t.messages.push({role:'bot',text:s.settings.approval?'The demo handoff is prepared. Review its sources and proposed destination before approving.':'The demo handoff is prepared. No external action has been executed.'});}t.events.push({text:{running:t.stage===1?'Evidence agent started.':'Handoff agent started.',waiting:'Waiting for supporting evidence.',review:'Demo output ready for review.',completed:'Demo run completed.'}[t.status],at:new Date().toISOString()});log(t.events.at(-1).text,t.id);emit()},
reply(id,text,files=[]){const t=task(id);if(['cancelled','completed'].includes(t.status))throw Error('This task is closed. Start a new task to continue.');if(!text.trim()&&!files.length)throw Error('Add a message or a document.');t.messages.push({role:'user',text:text.trim()||(files.length+' document(s) attached')});t.files.push(...files);t.events.push({text:'Additional information received.',at:new Date().toISOString()});if(t.status==='waiting'&&t.files.length){t.status='running';t.stage=1;}if(t.status==='review'){t.status='running';t.stage=1;t.output=null;t.approved=false;}log('Task context updated',id);emit()},
action(id,action){const t=task(id);if(action==='pause'&&t.status==='running')t.status='paused';else if(action==='resume'&&t.status==='paused')t.status='running';else if(action==='cancel'&&!['completed','cancelled'].includes(t.status))t.status='cancelled';else if(action==='approve'&&t.status==='review'){t.status='completed';t.approved=true;}else throw Error('This action is unavailable for the current task state.');log('Demo task '+t.status,id);t.events.push({text:'Task '+t.status,at:new Date().toISOString()});emit()},
saveSchedule(data,id){if(!data.name?.trim()||!data.prompt?.trim()||!/^\d{2}:\d{2}$/.test(data.time)||!['daily','weekdays','weekly'].includes(data.frequency))throw Error('Enter a name, task, frequency and valid time.');const next={...data,id:id||uid(),enabled:data.enabled!==false,lastRun:null};if(id){const i=s.schedules.findIndex(x=>x.id===id);if(i<0)throw Error('Schedule not found.');next.lastRun=s.schedules[i].lastRun;s.schedules[i]=next;}else s.schedules.push(next);log('Schedule saved: '+next.name);emit();return next.id},
toggleSchedule(id){const x=s.schedules.find(x=>x.id===id);if(!x)throw Error('Schedule not found.');x.enabled=!x.enabled;emit()},deleteSchedule(id){s.schedules=s.schedules.filter(x=>x.id!==id);emit()},
runSchedule(id){const x=s.schedules.find(x=>x.id===id);if(!x)throw Error('Schedule not found.');const tid=api.createTask(x.prompt,'Schedule · '+x.name,[],x.requiresDocument);x.lastRun=new Date().toISOString();emit();return tid},
receiveSlack(text,files=[]){if(!text.trim()&&!files.length)throw Error('Add a message or file.');const id=api.createTask(text||'Process the attached doctor document','Slack demo · Dr. Chen',files,false);s.inbox.unshift({id:uid(),taskId:id,text:text||'Document shared',files,at:new Date().toISOString(),author:'Dr. Chen'});log('Simulated Slack request received',id);emit();return id},
settings(data){if(!data.clinic?.trim())throw Error('Enter a clinic name.');try{new Intl.DateTimeFormat('en',{timeZone:data.timezone})}catch{throw Error('Enter a valid timezone, such as America/New_York.')}s.settings={...s.settings,...data};log('Workspace preferences updated');emit()},
reset(){s=initial();emit()}
};return api;}
root.CadenceOperations={create};if(typeof module!=='undefined')module.exports=root.CadenceOperations;
})(typeof window!=='undefined'?window:globalThis);
