/* Role-scoped Weaver chat for the clinical and patient workspaces. */
(()=>{
const role=()=>model.state.role==='patient'?'Patient':'Clinician';const key=()=>`cadence-${role().toLowerCase()}-chat`;let open=false,messages=[],currentRole='',busy=false,transient=null,poseTimer;
const pose=p=>`<span class="weaver-pose" data-pose="${p}" role="img" aria-label="Weaver ${p}">${WeaverWork.markup()}</span>`;
const launcher=document.createElement('button');launcher.id='weaver-launcher';launcher.setAttribute('aria-controls','weaver-panel');document.body.append(launcher);
const panel=document.createElement('section');panel.id='weaver-panel';panel.hidden=true;panel.setAttribute('aria-label',role()+' chat');document.body.append(panel);
function load(){try{messages=JSON.parse(localStorage.getItem(key())||'[]');if(!Array.isArray(messages))messages=[]}catch{messages=[]}}
function save(){messages=messages.slice(-40);try{localStorage.setItem(key(),JSON.stringify(messages))}catch{}}
function paint(){const log=panel.querySelector('.weaver-chat-log');if(!log)return;log.innerHTML=(messages.length?messages:[{who:'agent',text:role()==='Patient'?'Hello, I’m Weaver. I can help you find your check-in, explain the next step, or show your visit status.':'Hello, I’m Weaver. I can show what this encounter needs and guide you to summary review or documents.'}]).map(m=>`<div class="weaver-bubble ${m.who==='user'?'user':'agent'}"><small>${m.who==='user'?'You':'Weaver'}</small>${esc(m.text)}</div>`).join('');log.scrollTop=log.scrollHeight;}
function currentPose(){if(WeaverWork.greeting)return 'greeting';if(WeaverWork.celebrating)return 'celebrating';if(WeaverWork.active||['ASSEMBLING','VERIFYING'].includes(model.state.packet))return 'weaving';if(transient)return transient;const s=model.state;if(role()==='Patient')return s.checkedIn?'complete':'welcome';if(s.packet==='ASSEMBLING'||s.packet==='VERIFYING')return 'weaving';if(s.packet==='READY_FOR_COORDINATOR_REVIEW')return 'complete';if(s.request&&!s.document)return 'waiting';if(s.document)return 'document';if(s.transcript&&!s.review)return 'thinking';if(s.review)return 'complete';return 'welcome'}
function refreshPoses(){const p=currentPose();document.querySelectorAll('[data-weaver-avatar] .weaver-pose').forEach(n=>{if(n.dataset.pose!==p){n.dataset.pose=p;n.setAttribute('aria-label','Weaver '+p)}})}
function setPose(p){transient=p;clearTimeout(poseTimer);refreshPoses();poseTimer=setTimeout(()=>{transient=null;refreshPoses()},2400)}
function shell(){const changed=currentRole!==role();if(!changed)return;currentRole=role();transient=null;clearTimeout(poseTimer);load();launcher.innerHTML=`<span class="launcher-character" data-weaver-avatar>${pose('welcome')}</span><span class="launcher-copy"><strong>${role()} chat</strong><small>With Weaver</small></span>`;panel.setAttribute('aria-label',role()+' chat');panel.innerHTML=`<header class="weaver-chat-header"><span data-weaver-avatar>${pose('listening')}</span><div><h2>${role()} chat</h2><p>With Weaver · Your day, finding its rhythm.</p></div><button type="button" class="role-chat-close" aria-label="Close chat">×</button></header><div class="weaver-chat-log" role="log" aria-live="polite"></div><div class="weaver-chat-chips"><button type="button" data-role-chat-prompt="What is my current status?">Current status</button><button type="button" data-role-chat-prompt="What should I do next?">Next step</button></div><form class="weaver-chat-composer" id="role-chat-form"><label class="sr-only" for="role-chat-message">Message Weaver</label><textarea id="role-chat-message" maxlength="2000" placeholder="Ask Weaver about your ${role()==='Patient'?'visit':'encounter'}…" required></textarea><div class="weaver-chat-actions"><button class="primary" type="submit">Send</button></div><p class="weaver-chat-note">Prototype guidance · Live agent is not connected</p></form>`;paint()}
function toggle(value){open=value;document.body.classList.toggle('weaver-chat-open',value);if(value)WeaverWork.greet();panel.hidden=!value;launcher.hidden=value;launcher.setAttribute('aria-expanded',String(value));if(value)panel.querySelector('textarea').focus();else launcher.focus()}
function answer(text){const s=model.state;if(/^(hi|hello|hey|thanks)[!. ]*$/i.test(text))return 'I’m here to help. Ask about your status or the next step.';if(/status|next|check.?in|document|summary|review|visit|help/i.test(text)){if(role()==='Patient')return s.checkedIn?'You are checked in. Your administrative details and acknowledgment are recorded in this prototype. Open Activity to see the visit history.':'Open Your visit, confirm your administrative details and acknowledgment, then select the check-in button. Your clinician handles the encounter review.';return model.unresolved.length?'This encounter still needs: '+model.unresolved.map(r=>r.item+' ('+r.owner+')').join('; ')+'. Use the encounter workspace for summary review or Documents for the signed file.':'The encounter’s required fixture evidence is present. Coordinator work continues in the main Coordinator workspace.';}return 'I’ve kept your message in this '+role().toLowerCase()+' conversation. General answers and real agent execution require the backend connection. In this prototype, I can show your current status and explain the next step.'}
launcher.addEventListener('click',()=>toggle(true));panel.addEventListener('click',e=>{if(e.target.closest('.role-chat-close'))toggle(false);const chip=e.target.closest('[data-role-chat-prompt]');if(chip){panel.querySelector('textarea').value=chip.dataset.roleChatPrompt;panel.querySelector('form').requestSubmit()}});
panel.addEventListener('submit',e=>{e.preventDefault();e.stopPropagation();if(busy)return;const input=panel.querySelector('textarea'),text=input.value.trim();if(!text)return;messages.push({who:'user',text},{who:'agent',text:answer(text)});input.value='';save();paint();WeaverWork.celebrate()},true);
panel.addEventListener('input',()=>setPose('listening'));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&open)toggle(false)});let previousMilestones={checkedIn:model.state.checkedIn,completed:model.state.completed,packet:model.state.packet};model.subscribe(()=>{const s=model.state;const finished=(role()==='Patient'&&s.checkedIn&&!previousMilestones.checkedIn)||(role()==='Clinician'&&((s.completed&&!previousMilestones.completed)||(s.packet==='READY_FOR_COORDINATOR_REVIEW'&&previousMilestones.packet!==s.packet)));previousMilestones={checkedIn:s.checkedIn,completed:s.completed,packet:s.packet};shell();if(finished)WeaverWork.celebrate();refreshPoses()});shell();
function companionCopy(){const s=model.state,route=location.hash.slice(1);if(route==='timeline')return ['Every step stays connected.','Ask me about your visit or encounter status.'];if(role()==='Patient')return s.checkedIn?['You’re checked in.','Your details are woven into the visit. Ask me what comes next.']:['Let’s get you settled in.','I’m here if you need help with your details or check-in.'];if(route==='documents')return s.document?['A new thread, connected.','Your document has arrived. Follow the handoff as it takes shape.']:['Let’s bring the evidence together.','Ask me what is needed, then attach the signed document here.'];if(route==='review')return s.review?['The summary has your review.','Continue the encounter when you’re ready.']:['A little attention to every detail.','Review the source and the exact summary before accepting.'];if(s.packet==='READY_FOR_COORDINATOR_REVIEW')return ['The handoff is woven together.','The required fixture evidence is ready.'];if(s.request&&!s.document)return ['There’s a thread missing.','The signed document will let the work continue.'];return ['Let’s bring this encounter together.','Ask me what needs your attention or what comes next.']}
function addCompanion(){const app=$('#app');if(!app||app.querySelector('.weaver-context'))return;const copy=companionCopy(),button=document.createElement('button');button.className='weaver-context';button.setAttribute('aria-label','Open '+role()+' chat with Weaver');button.innerHTML=`<span data-weaver-avatar>${pose(currentPose())}</span><span><strong>${esc(copy[0])}</strong><small>${esc(copy[1])}</small></span>`;button.addEventListener('click',()=>toggle(true));app.querySelector('.page-heading')?.after(button);refreshPoses()}
let greetingRoute=location.hash;const originalRender=render;render=function(...args){const previous=document.querySelector('.weaver-context [data-weaver-avatar]');originalRender(...args);addCompanion();const next=document.querySelector('.weaver-context [data-weaver-avatar]');if(previous&&next){next.replaceWith(previous);refreshPoses()}if(greetingRoute!==location.hash){greetingRoute=location.hash;WeaverWork.greet()}};addCompanion();
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');let frame=0,point={x:0,y:0},idle=0;
document.addEventListener('pointermove',e=>{if(reduced.matches||e.pointerType==='touch')return;point={x:e.clientX,y:e.clientY};if(frame)return;frame=requestAnimationFrame(()=>{frame=0;document.querySelectorAll('[data-weaver-avatar]').forEach(n=>{const r=n.getBoundingClientRect(),dx=Math.max(-1,Math.min(1,(point.x-r.left-r.width/2)/250)),dy=Math.max(-1,Math.min(1,(point.y-r.top-r.height/2)/250));n.style.setProperty('--look-x',dx*3+'px');n.style.setProperty('--look-y',dy*2+'px');n.style.setProperty('--look-turn',dx*4+'deg')})})},{passive:true});
document.addEventListener('visibilitychange',()=>document.body.classList.toggle('weaver-tab-hidden',document.hidden));
document.addEventListener('input',e=>{if(e.target.matches('textarea,input[type=text]'))setPose('listening')});
document.addEventListener('change',e=>{if(e.target.type==='file'&&e.target.files?.length)setPose('document');else if(e.target.type==='checkbox')setPose('listening')});
launcher.addEventListener('pointerenter',()=>setPose('welcome'));
setInterval(()=>{if(document.hidden||reduced.matches||transient||currentPose()!=='welcome')return;idle++;setPose(idle%3===0?'thinking':idle%2===0?'welcome':'listening')},6500);
document.addEventListener('weaver-work-change',refreshPoses);
WeaverWork.greet();
})();
