/* The Weaver: stateful UI companion. Responses are deterministic demo behavior. */
(()=>{
const pose=(state='welcome')=>`<span class="weaver-pose" data-pose="${state}" role="img" aria-label="The Weaver, ${state}">${WeaverWork.markup()}</span>`;
let messages=[];try{messages=JSON.parse(localStorage.getItem('cadence-weaver-chat')||'[]');if(!Array.isArray(messages))messages=[]}catch{}let open=false,busy=false,transient=null,transientTimer;
const save=()=>{messages=messages.slice(-50);try{localStorage.setItem('cadence-weaver-chat',JSON.stringify(messages))}catch{}};
function activeTask(){const route=location.hash.slice(1);return route.startsWith('task/')?ops.state.tasks.find(t=>t.id===route.slice(5)):ops.state.tasks.find(t=>['running','waiting','review'].includes(t.status))}
function state(){if(WeaverWork.greeting)return 'greeting';if(WeaverWork.celebrating)return 'celebrating';if(WeaverWork.active||busy||activeTask()?.status==='running')return 'weaving';if(transient)return transient;const t=activeTask();return t?({running:'weaving',waiting:'waiting',review:'complete',completed:'complete',paused:'resting',cancelled:'resting'}[t.status]||'welcome'):'welcome'}
function cue(p){transient=p;clearTimeout(transientTimer);refreshPoses();transientTimer=setTimeout(()=>{transient=null;refreshPoses()},2600)}
function refreshPoses(){const next=state();document.querySelectorAll('[data-weaver-avatar]').forEach(n=>{const character=n.querySelector('.weaver-pose');if(character){if(character.dataset.pose!==next){character.dataset.pose=next;character.setAttribute('aria-label','The Weaver, '+next)}}else n.innerHTML=pose(next)})}
const launcher=document.createElement('button');launcher.id='weaver-launcher';launcher.setAttribute('aria-controls','weaver-panel');launcher.setAttribute('aria-expanded','false');launcher.innerHTML=`<span class="launcher-character" data-weaver-avatar>${pose()}</span><span class="launcher-copy"><strong>Coordinator chat</strong><small>Your clinic companion</small></span>`;document.body.append(launcher);
const panel=document.createElement('section');panel.id='weaver-panel';panel.hidden=true;panel.setAttribute('aria-label','Coordinator chat with Weaver');panel.innerHTML=`<header class="weaver-chat-header"><span data-weaver-avatar>${pose()}</span><div><h2>Coordinator chat</h2><p>Your day, finding its rhythm.</p></div><button id="weaver-close" aria-label="Close Weaver chat">×</button></header><div class="weaver-chat-log" role="log" aria-live="polite" aria-label="Conversation"></div><div class="weaver-chat-chips"><button data-weaver-prompt="What needs my attention?">Needs attention</button><button data-weaver-prompt="Help me create a schedule">Create a schedule</button><button data-weaver-prompt="Prepare the handoff for encounter 104">New task</button></div><form id="weaver-chat-form" class="weaver-chat-composer"><label class="sr-only" for="weaver-message">Message Weaver</label><textarea id="weaver-message" name="message" maxlength="2000" placeholder="Ask a question or describe the work…"></textarea><div class="weaver-chat-files"></div><div class="weaver-chat-actions"><label>＋ Document<input type="file" name="files" multiple accept=".txt,.pdf,.csv,.md" aria-label="Attach synthetic document"></label><button type="button" class="weaver-mic" aria-label="Speak to Weaver" title="Speak (transcribed on the GB10 by NVIDIA Parakeet)">🎙</button><button class="primary" type="submit">Send</button></div><p class="weaver-chat-error" role="alert"></p><p class="weaver-chat-note">Demo companion · Synthetic data only · <span class="weaver-runtime">Agent runtime offline</span></p><button type="button" class="weaver-chat-clear">Clear conversation</button></form>`;document.body.append(panel);
function paintChat(){const log=panel.querySelector('.weaver-chat-log');log.innerHTML=(messages.length?messages:[{role:'agent',text:'Hello, I’m Weaver. Tell me what needs doing, ask about your tasks, or attach a document. I can help you navigate and create tasks in this demo workspace.'}]).map((m,i)=>`<div class="weaver-bubble ${m.role==='user'?'user':'agent'}"><small>${m.role==='user'?'You':'Weaver'}</small>${esc(m.text)}${m.taskId?`<a class="weaver-task-link" href="#task/${encodeURIComponent(m.taskId)}">Open task</a>`:''}${m.route?`<a class="weaver-task-link" href="#${m.route}">${esc(m.linkLabel||'Open view')}</a>`:''}${m.proposal?`<button class="chat-task-button" data-chat-assign="${i}" ${m.assigned?'disabled':''}>${m.assigned?'Task assigned':'Assign this as a task'}</button>`:''}</div>`).join('')+(busy?'<div class="weaver-typing">Weaver is gathering the context…</div>':'');log.scrollTop=log.scrollHeight;}
function toggle(value){open=value;panel.hidden=!value;launcher.hidden=value;launcher.setAttribute('aria-expanded',String(value));document.body.classList.toggle('weaver-chat-open',value);if(value){paintChat();WeaverWork.greet();panel.querySelector('textarea').focus()}else launcher.focus()}
launcher.addEventListener('click',()=>toggle(true));panel.querySelector('#weaver-close').addEventListener('click',()=>toggle(false));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&open){toggle(false)}});
function answer(text,files){const lower=text.toLowerCase(),ts=ops.state.tasks;if(/attention|status|progress|what.*tasks|working on/.test(lower)&&!files.length){const attention=ts.filter(t=>['waiting','review','running','paused'].includes(t.status));return {role:'agent',text:attention.length?attention.map(t=>`${t.title}: ${statuses[t.status]}.`).join('\n'):'There are no open tasks needing attention. Describe the next task and I’ll help you start it.',route:'tasks',linkLabel:'View all tasks'}}if(/schedule/.test(lower)&&!files.length)return {role:'agent',text:'Set the task, recurrence and time in Schedules. You can edit, pause or run a schedule immediately. Demo schedules run only while this page is open.',route:'schedules',linkLabel:'Open schedules'};if(/slack|connect|gb10|local system/.test(lower)&&!files.length)return {role:'agent',text:'Slack, the GB10 agent runtime and local-system delivery are not connected yet. You can explore the doctor inbox preview and see the integration requirements in Connections.',route:'connections',linkLabel:'View connections'};if(/^(hi|hello|hey|thanks|thank you)[!. ]*$/.test(lower)&&!files.length)return {role:'agent',text:'I’m here. Tell me what you’d like to take care of, or ask what needs your attention.'};return {role:'agent',text:'I can turn this into a tracked demo task and bring together the planner, evidence and handoff agents. Review your request below, then assign it when ready.\n\n'+(text||'Process the attached document')+'\n\n'+(files.length?files.length+' document(s) attached. Only file metadata and hashes are kept.':'For general answers and real execution, the agent backend still needs to be connected.'),proposal:{text:text||'Process the attached document',files}}}
panel.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();if(busy)return;const form=e.target,text=form.message?.value||form.querySelector('textarea').value;const filesInput=form.querySelector('input[type=file]');if(!text.trim()&&!filesInput.files.length)return;let answerReady=false;const finishChatWork=WeaverWork.begin();busy=true;form.querySelector('.primary').disabled=true;form.querySelector('.weaver-chat-error').textContent='';cue('thinking');try{const files=await filesOf(form);messages.push({role:'user',text:text.trim()+(files.length?'\nAttached: '+files.map(f=>f.name).join(', '):'')});form.reset();form.querySelector('.weaver-chat-files').textContent='';paintChat();messages.push(await liveAnswer(text.trim(),files));answerReady=true;save();cue(files.length?'document':'listening')}catch(err){form.querySelector('.weaver-chat-error').textContent=err.message}finally{busy=false;form.querySelector('.primary').disabled=false;paintChat();if(answerReady)WeaverWork.celebrate();finishChatWork();refreshPoses()}},true);
panel.addEventListener('click',e=>{const prompt=e.target.closest('[data-weaver-prompt]'),assign=e.target.closest('[data-chat-assign]');if(prompt){panel.querySelector('textarea').value=prompt.dataset.weaverPrompt;panel.querySelector('form').requestSubmit()}if(assign){const m=messages[Number(assign.dataset.chatAssign)];if(!m?.proposal||m.assigned)return;const id=ops.createTask(m.proposal.text,'Weaver chat',m.proposal.files,/document|handoff|evidence/i.test(m.proposal.text)&&!m.proposal.files.length);m.assigned=true;messages.push({role:'agent',text:'The demo task is underway. Follow the swarm, add context, or pause it in the task workspace.',taskId:id});save();paintChat();cue('weaving');go('task/'+id)}});
panel.querySelector('textarea').addEventListener('input',()=>cue('listening'));panel.querySelector('input[type=file]').addEventListener('change',e=>{panel.querySelector('.weaver-chat-files').textContent=Array.from(e.target.files).map(f=>f.name).join(', ');cue('document')});panel.querySelector('.weaver-chat-clear').addEventListener('click',()=>{messages=[];save();paintChat();cue('welcome')});
function addCompanion(){const app=$('#app');if(!app||app.querySelector('.weaver-context'))return;const route=location.hash.slice(1)||'home',t=activeTask();const copy=route.startsWith('task/')?{running:['I’m weaving the work together.','Open chat for help or add context to the task below.'],waiting:['There’s a thread missing.','Add supporting evidence to continue this task.'],review:['The handoff is ready for your review.','Check the output before approving.'],completed:['All woven together.','The demo task is complete.'],paused:['Taking a pause.','Resume the task when you’re ready.'],cancelled:['This task has been set aside.','Start a new task whenever you’re ready.']}[t?.status]:{home:['What shall we work on today?','Chat with me from anywhere in your workspace.'],tasks:['Every thread has a place.','Ask me which tasks need your attention.'],schedules:['Let’s find your clinic’s rhythm.','I can help you get to the schedule controls.'],inbox:['A little context goes a long way.','Doctor requests come together here.'],connections:['Ready to connect the next thread.','See what still needs a backend connection.'],activity:['Here’s how the work unfolded.','Your task history stays in view.'],settings:['Make yourself at home.','Shape the workspace around your clinic.']}[route];const b=document.createElement('button');b.className='weaver-context';b.innerHTML=`<span data-weaver-avatar>${pose(state())}</span><span><strong>${esc(copy?.[0]||'I’m here to help.')}</strong><small>${esc(copy?.[1]||'Open Weaver chat.')}</small></span>`;b.addEventListener('click',()=>toggle(true));app.querySelector('.ops-heading')?.after(b);refreshPoses()}
let greetingRoute=location.hash;const originalRender=render;render=function(...args){const previous=document.querySelector('.weaver-context [data-weaver-avatar]');originalRender(...args);addCompanion();const next=document.querySelector('.weaver-context [data-weaver-avatar]');if(previous&&next){next.replaceWith(previous);refreshPoses()}if(greetingRoute!==location.hash){greetingRoute=location.hash;WeaverWork.greet()}};const previousStatuses=new Map(ops.state.tasks.map(t=>[t.id,t.status]));ops.subscribe(()=>{let completed=false;for(const task of ops.state.tasks){if(task.status==='completed'&&previousStatuses.has(task.id)&&previousStatuses.get(task.id)!=='completed')completed=true;previousStatuses.set(task.id,task.status)}if(completed)WeaverWork.celebrate();refreshPoses();if(open)paintChat()});addCompanion();paintChat();
// Pointer attention is kept separate from pose animation, and never rebuilds the sprite.
const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');
let pointerFrame=0,point={x:0,y:0},idleBeat=0;
document.addEventListener('pointermove',event=>{
if(motionPreference.matches||event.pointerType==='touch')return;
point={x:event.clientX,y:event.clientY};if(pointerFrame)return;
pointerFrame=requestAnimationFrame(()=>{pointerFrame=0;document.querySelectorAll('[data-weaver-avatar]').forEach(n=>{const r=n.getBoundingClientRect();const dx=Math.max(-1,Math.min(1,(point.x-r.left-r.width/2)/250)),dy=Math.max(-1,Math.min(1,(point.y-r.top-r.height/2)/250));n.style.setProperty('--look-x',dx*3+'px');n.style.setProperty('--look-y',dy*2+'px');n.style.setProperty('--look-turn',dx*4+'deg')})});
},{passive:true});
document.addEventListener('visibilitychange',()=>document.body.classList.toggle('weaver-tab-hidden',document.hidden));
launcher.addEventListener('pointerenter',()=>{if(!busy)cue('welcome')});
// Quiet moments include a glance and a return to attention; task poses stay truthful.
setInterval(()=>{if(document.hidden||motionPreference.matches||busy||transient||activeTask())return;idleBeat++;cue(idleBeat%3===0?'thinking':idleBeat%2===0?'welcome':'listening')},6500);
document.addEventListener('input',event=>{if(event.target.matches('textarea')&&!panel.contains(event.target))cue('listening')});
document.addEventListener('change',event=>{if(event.target.type==='file'&&event.target.files?.length)cue('document')});
document.addEventListener('weaver-work-change',refreshPoses);
WeaverWork.greet();
/* Live GB10 agent + voice (Cadence service). Falls back to the local demo answers when the service is unreachable. */
let liveOk=false,spokenTurn=false
async function liveAnswer(text,files){if(!liveOk||files.length)return answer(text,files)
try{const history=messages.slice(0,-1).slice(-8).map(m=>({role:m.role==='user'?'user':'assistant',content:m.text}))
const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,history})})
if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||'agent unavailable')
const d=await r.json();if(spokenTurn)speak(d.reply);return {role:'agent',text:d.reply,route:'activity',linkLabel:'See agent activity'}}catch(err){return {role:'agent',text:'The GB10 agent is busy right now ('+err.message+'). '+answer(text,files).text}}finally{spokenTurn=false}}
function speak(text){try{if(!('speechSynthesis' in window)||!speechSynthesis.getVoices().length)return
const u=new SpeechSynthesisUtterance(String(text).replace(/[*_`#]/g,'').slice(0,600));u.rate=1.05;speechSynthesis.cancel();speechSynthesis.speak(u)}catch{}}
fetch('/api/health').then(r=>r.ok?r.json():null).then(h=>{if(!h)return;liveOk=h.vllm==='ok'
const el=panel.querySelector('.weaver-runtime');if(el)el.textContent=liveOk?'Live agent on GB10 · local inference':'Agent runtime offline'}).catch(()=>{})
;(()=>{const mic=panel.querySelector('.weaver-mic');if(!mic)return
let rec=null,chunks=[]
mic.addEventListener('click',async()=>{if(rec&&rec.state==='recording'){rec.stop();return}
const err=panel.querySelector('.weaver-chat-error');err.textContent=''
try{const stream=await navigator.mediaDevices.getUserMedia({audio:true})
rec=new MediaRecorder(stream);chunks=[]
rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)}
rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());mic.classList.remove('recording');mic.textContent='…';cue('thinking')
const finish=WeaverWork.begin()
try{const fd=new FormData();fd.append('file',new Blob(chunks,{type:rec.mimeType||'audio/webm'}),'speech.webm')
const r=await fetch('/api/voice/command',{method:'POST',body:fd});if(!r.ok)throw new Error('speech service unavailable')
const d=await r.json();if(!d.text){err.textContent='I didn’t catch that. Try again.';return}
panel.querySelector('textarea').value=d.text;spokenTurn=true;panel.querySelector('form').requestSubmit()}
catch(e2){err.textContent=e2.message}finally{mic.textContent='🎙';finish();refreshPoses()}}
rec.start();mic.classList.add('recording');mic.textContent='■';cue('listening')}catch(e1){err.textContent='Microphone unavailable: '+e1.message}})})()
})();
